[package]
name = "superchain-registry"
version = "0.1.0"
authors = ["OP Contributors"]
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
include_dir = { version = "0.7.3" }
serde_repr = "0.1"
serde_yaml = "0.9"
serde_json = "1.0"
lazy_static = "1.4.0"
