run:
  timeout: 5m

linters:
  # also see https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gofumpt
    - goimports
    - bodyclose
    - asciicheck
    - misspell
    - errorlint
