[tools]

# Core dependencies
go = "1.23.1"
just = "1.37.0"

# Go dependencies
"go:gotest.tools/gotestsum" = "1.12.0"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "1.61.0"

[settings]
experimental = true