l1_cross_domain_messenger: 1.1.0
l1_erc721_bridge: 1.1.0
l1_standard_bridge: 1.1.0
l2_output_oracle: 1.2.0
optimism_mintable_erc20_factory: 1.1.0
optimism_portal: 1.2.0
system_config: 1.0.1

# superchain-wide contracts
protocol_versions: 0.1.0