name = "SlipChain"
short_name = "slipchain"
superchain = "sepolia"
public_rpc = "https://foo.bar.net"
sequencer_rpc = "https://foo.bar.net"
explorer = "https://foo.bar.net"
superchain_level = 0
governed_by_optimism = false
superchain_time = 0
data_availability_type = "eth-da"
deployment_tx_hash = "0x0193884dc77ba74ca9ae23079edf91b81d49b0243c486fab5bbecd415d2dad68"
