["op-contracts/v1.6.0"] # Fault Proof Fixes https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.6.0
address_manager = ""
l1_cross_domain_messenger = "2.3.0"
l1_erc721_bridge = "2.1.0"
l1_standard_bridge = "2.1.0"
optimism_mintable_erc20_factory = "1.9.0"
optimism_portal = "3.10.0"
system_config = "2.2.0"
protocol_versions = "1.0.0"
anchor_state_registry = "2.0.0"
delayed_weth = "1.1.0"
dispute_game_factory = "1.0.0"
fault_dispute_game = "1.3.0"
permissioned_dispute_game = "1.3.0"
mips = "1.1.0"
pre_image_oracle = "1.1.2"
deputy_guardian_module = "2.0.0"
