["op-contracts/v1.1.0"]
optimism_mintable_erc20_factory = "1.1.0"
optimism_portal = "1.6.0"
system_config = "1.3.0"
l2_output_oracle = "1.3.0"
l1_erc721_bridge = "1.1.1"
l1_standard_bridge = "1.1.0"
address_manager = ""
l1_cross_domain_messenger = "1.4.0"
protocol_versions = "1.0.0"

["op-contracts/v1.0.0"]
optimism_mintable_erc20_factory = "1.1.0"
optimism_portal = "1.6.0"
system_config = "1.3.0"
l2_output_oracle = "1.3.0"
l1_erc721_bridge = "1.1.1"
l1_standard_bridge = "1.1.0"
address_manager = ""
l1_cross_domain_messenger = "1.4.0"
