standard_release = "op-contracts/v1.6.0"

[releases]

# Contracts which are
#   * unproxied singletons: specify a standard "address"
#   * proxied             : specify a standard "implementation_address"
#   * neither             : specify neither a standard "address" nor "implementation_address"

# Fault Proofs https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.6.0
[releases."op-contracts/v1.6.0"]
optimism_portal = { version = "3.10.0", implementation_address = "0x" }
system_config = { version = "2.2.0", implementation_address = "0x" }
anchor_state_registry = { version = "2.0.0" }
delayed_weth = { version = "1.1.0", implementation_address = "0x" }
dispute_game_factory = { version = "1.0.0", implementation_address = "0x" }
fault_dispute_game = { version = "1.3.0" }
permissioned_dispute_game = { version = "1.3.0" }
mips = { version = "1.1.0", address = "0x" }
preimage_oracle = { version = "1.1.2", address = "0x" }
l1_cross_domain_messenger = { version = "2.3.0", implementation_address = "0x" }
l1_erc721_bridge = { version = "2.1.0", implementation_address = "0x" }
l1_standard_bridge = { version = "2.1.0", implementation_address = "0x" }
# l2_output_oracle -- This contract not used in fault proofs
optimism_mintable_erc20_factory = { version = "1.9.0", implementation_address = "0x" }
