["op-contracts/v1.4.0-rc.3"]
optimism_mintable_erc20_factory = "1.9.0"
optimism_portal = "3.8.0"
system_config = "2.2.0"
l1_erc721_bridge = "2.1.0"
l1_standard_bridge = "2.1.0"
address_manager = ""
l1_cross_domain_messenger = "2.3.0"
protocol_versions = "1.0.0"
anchor_state_registry = "1.0.0"
delayed_weth = "1.0.0"
dispute_game_factory = "1.0.0"

["op-contracts/v1.4.0-rc.2"]
optimism_mintable_erc20_factory = "1.9.0"
optimism_portal = "3.8.0"
system_config = "2.0.0"
l1_erc721_bridge = "2.1.0"
l1_standard_bridge = "2.1.0"
address_manager = ""
l1_cross_domain_messenger = "2.3.0"
protocol_versions = "1.0.0"
anchor_state_registry = "1.0.0"
delayed_weth = "1.0.0"
dispute_game_factory = "1.0.0"

["op-contracts/v1.3.0"]
optimism_mintable_erc20_factory = "1.9.0"
optimism_portal = "2.5.0"
system_config = "1.12.0"
l2_output_oracle = "1.8.0"
l1_erc721_bridge = "2.1.0"
l1_standard_bridge = "2.1.0"
address_manager = ""
l1_cross_domain_messenger = "2.3.0"
protocol_versions = "1.0.0"

["op-contracts/v1.2.0"]
optimism_mintable_erc20_factory = "1.8.0"
optimism_portal = "2.4.0"
system_config = "1.11.0"
l2_output_oracle = "1.7.0"
l1_erc721_bridge = "2.0.0"
l1_standard_bridge = "2.0.0"
address_manager = ""
l1_cross_domain_messenger = "2.2.0"
protocol_versions = "1.0.0"

["op-contracts/v1.1.0"]
optimism_mintable_erc20_factory = "1.1.0"
optimism_portal = "1.6.0"
system_config = "1.3.0"
l2_output_oracle = "1.3.0"
l1_erc721_bridge = "1.1.1"
l1_standard_bridge = "1.1.0"
address_manager = ""
l1_cross_domain_messenger = "1.4.0"
protocol_versions = "1.0.0"

["op-contracts/v1.0.0"]
optimism_mintable_erc20_factory = "1.1.0"
optimism_portal = "1.6.0"
system_config = "1.3.0"
l2_output_oracle = "1.3.0"
l1_erc721_bridge = "1.1.1"
l1_standard_bridge = "1.1.0"
address_manager = ""
l1_cross_domain_messenger = "1.4.0"
