l1_cross_domain_messenger: 2.3.0
l1_erc721_bridge: 1.1.2
l1_standard_bridge: 1.1.1
l2_output_oracle: 1.8.0
optimism_mintable_erc20_factory: 1.1.1
optimism_portal: 1.7.2
system_config: 1.3.1

# superchain-wide contracts
protocol_versions: 1.0.0 # TODO
superchain_config: 1.1.0
