name: Sepolia Seal 0
l1:
  chain_id: 11155111
  public_rpc: https://eth-sepolia.g.alchemy.com/v2/9PqDKhFhwoeNRoRLkSGoZ7Kz6hTdTwv6
  explorer: https://sepolia.etherscan.io

protocol_versions_addr: null # todo
superchain_config_addr: "0xAF5F519F28D0e0125bd71829aaE7Fb5519D15160" # todo
