name: sealchain-2
chain_id: 6619
public_rpc: https://rpc-seal-rollup-base-rgf4y72ymx.t.conduit.xyz
sequencer_rpc: https://rpc.seal-base.securityalliance.dev/sequencer
explorer: https://explorerl2new-seal-rollup-base-rgf4y72ymx.t.conduit.xyz

superchain_level: 2
superchain_time: 0 # Missing hardfork times are inherited from superchain.yaml

batch_inbox_addr: 0x6437cb4f91ce43c70c2303d5673a659c6d62e9bf
system_config_addr: 0xe01AA5c653C56FDA3299756bBf3505DC47774476

genesis:
  l1:
    hash: 0x0f9ebf6fd51e23f2c60e6ed0a2e8ea62cdf3804e2b24f62420104d8eb54df08c
    number: 5851659
  l2:
    hash: 0x8651dd859765554ab0fd846b4f16e235e25c86c83cacff5862b43b0cdc9ad45d
    number: 0
  l2_time: 1715039268 # Mon 6 May 2024 23:47:48 UTC

canyon_time: 0 # Thu 1 Jan 1970 00:00:00 UTC
delta_time: 0 # Thu 1 Jan 1970 00:00:00 UTC
ecotone_time: 0 # Thu 1 Jan 1970 00:00:00 UTC
