l1_cross_domain_messenger: 2.3.0
l1_erc721_bridge: 2.1.0
l1_standard_bridge: 2.1.0
l2_output_oracle: 1.8.0
optimism_mintable_erc20_factory: 1.9.0
optimism_portal: 3.3.0
system_config: 1.12.0

# superchain-wide contracts
protocol_versions: 1.0.0
superchain_config: 1.1.0
