name: Base
chain_id: 8453
public_rpc: https://mainnet.base.org
sequencer_rpc: https://mainnet-sequencer.base.org
explorer: https://explorer.base.org

superchain_level: 1
standard_chain_candidate: true # This is a temporary field which causes most of the standard validation checks to run on this chain
superchain_time: 0 # Missing hardfork times are inherited from superchain.yaml
contracts_version_tag: op-contracts/v1.3.0 # Multi-Chain Prep (MCP) https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.3.0


system_config_addr: "0x73a79Fab69143498Ed3712e519A88a918e1f4072"
batch_inbox_addr: "0xFf00000000000000000000000000000000008453"

genesis:
  l1:  # L1 anchor-point of the rollup
    hash: "0x5c13d307623a926cd31415036c8b7fa14572f9dac64528e857a470511fc30771"
    number: 17481768
  l2:
    hash: "0xf712aa9241cc24369b143cf6dce85f0902a9731e70d66818a3a5845b296c73dd"
    number: 0
  l2_time: 1686789347 # Thu 15 Jun 2023 00:35:47 UTC
