name: Orderly Mainnet
chain_id: 291
public_rpc: https://rpc.orderly.network
sequencer_rpc: https://rpc.orderly.network
explorer: https://explorer.orderly.network

superchain_level: 1
superchain_time: 0 # Missing hardfork times are inherited from superchain.yaml

system_config_addr: "0x886B187C3D293B1449A3A0F23Ca9e2269E0f2664"
batch_inbox_addr: "0x08aA34cC843CeEBcC88A627F18430294aA9780be"

genesis:
  l1:  # L1 anchor-point of the rollup
    hash: "0x787d5dd296d63bc6e7a4158d4f109e1260740ee115f5ed5124b35dece1fa3968"
    number: 18292529
  l2:
    hash: "0xe53c94ddd42714239429bd132ba2fa080c7e5cc7dca816ec6e482ec0418e6d7f"
    number: 0
  l2_time: 1696608227 # Fri  6 Oct 2023 16:03:47 UTC

block_time: 2
seq_window_size: 3600
