l1_cross_domain_messenger: 2.2.0
l1_erc721_bridge: 2.0.0
l1_standard_bridge: 2.0.0
l2_output_oracle: 1.7.0
optimism_mintable_erc20_factory: 1.8.0
optimism_portal: 2.4.0
system_config: 1.11.0

# superchain-wide contracts
protocol_versions: 1.0.0
