name: Maintainer Approval

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  hold-for-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Received required maintainer approval. Proceeding to subsequent workflows..."
