name: Release Rust Crates

on:
  workflow_dispatch:

jobs:
  release-crates:
    name: Release Crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
      - name: Release Crates
        run: |
          cargo install cargo-release
          cargo login $CARGO_REGISTRY_TOKEN
          just release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
